import { useRef, useState } from 'react';
import { clearAdminData, emptyAdminData, readAdminData, saveAdminData } from './siteData';
import './admin.css';

const clone = (value) => JSON.parse(JSON.stringify(value));

function ArrowIcon({ direction = 'up-right' }) { return <i className={`fa-solid fa-arrow-${direction}`} aria-hidden="true" />; }
function AdminMark() { return <a className="admin-mark" href="/">8iT<span>// CONTROL ROOM</span></a>; }

function Field({ label, value, onChange, type = 'text', placeholder = '' }) {
  return <label className="admin-field"><span>{label}</span><input type={type} value={value ?? ''} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} /></label>;
}

function Panel({ number, title, copy, children }) {
  return <section className="admin-panel"><div className="admin-panel__head"><span>{number}</span><div><p className="admin-kicker">CONTROL // {number}</p><h2>{title}</h2><p>{copy}</p></div></div>{children}</section>;
}

export function Admin() {
  const [data, setData] = useState(() => clone(readAdminData()));
  const [message, setMessage] = useState('LOCAL OVERRIDES // NOT SAVED');
  const importRef = useRef(null);

  const updateEvent = (key, value) => setData((current) => ({ ...current, event: { ...current.event, [key]: value } }));
  const updateArrayCell = (section, rowIndex, cellIndex, value) => setData((current) => ({ ...current, [section]: current[section].map((row, index) => index === rowIndex ? row.map((cell, cellIndexToUpdate) => cellIndexToUpdate === cellIndex ? value : cell) : row) }));
  const updateLiveMatch = (key, value) => setData((current) => ({ ...current, liveMatch: { ...current.liveMatch, [key]: value } }));
  const updateBracketTitle = (roundIndex, value) => setData((current) => ({ ...current, bracket: current.bracket.map((round, index) => index === roundIndex ? { ...round, title: value } : round) }));
  const updateBracketCell = (roundIndex, rowIndex, cellIndex, value) => setData((current) => ({ ...current, bracket: current.bracket.map((round, index) => index === roundIndex ? { ...round, rows: round.rows.map((row, rowToUpdate) => rowToUpdate === rowIndex ? row.map((cell, cellToUpdate) => cellToUpdate === cellIndex ? value : cell) : row) } : round) }));

  const save = () => { saveAdminData(data); setMessage(`SAVED // ${new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`); };
  const reset = () => { if (!window.confirm('Reset all local event overrides to the starter data?')) return; clearAdminData(); setData(clone(emptyAdminData)); setMessage('RESET // STARTER DATA RESTORED'); };
  const exportData = () => { const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = '8it-event-data.json'; link.click(); URL.revokeObjectURL(url); setMessage('EXPORTED // 8it-event-data.json'); };
  const importData = (event) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const parsed = JSON.parse(reader.result); setData({ ...clone(emptyAdminData), ...parsed, event: { ...clone(emptyAdminData.event), ...(parsed.event || {}) }, liveMatch: { ...clone(emptyAdminData.liveMatch), ...(parsed.liveMatch || {}) } }); setMessage('IMPORTED // REVIEW THEN SAVE'); } catch { setMessage('IMPORT FAILED // INVALID JSON'); } }; reader.readAsText(file); event.target.value = ''; };

  return <div className="admin-page"><header className="admin-header"><AdminMark /><div className="admin-header__meta"><span><i /> EVENT-DAY CONTROL ROOM</span><small>EDIT FAST // SAVE ONCE // RUN THE ROOM</small></div><div className="admin-header__actions"><a href="/" target="_blank" rel="noreferrer">OPEN PUBLIC SITE <ArrowIcon /></a><a href="/shop.html" target="_blank" rel="noreferrer">OPEN SHOP <ArrowIcon /></a></div></header>
    <main className="admin-main"><section className="admin-hero"><div><p className="admin-kicker">8iT // ADMIN CONSOLE</p><h1>RUN THE<br /><em>ROOM.</em></h1><p>Change the unknowns when the tournament tells you what they are. Save locally, open the public site in another tab, and refresh only when you need a hard reset.</p></div><div className="admin-hero__status"><span>LIVE DATA SOURCE</span><strong>LOCAL OVERRIDES</strong><small>Public page reads the saved data from this browser.</small><div className="admin-actions"><button className="admin-button admin-button--primary" type="button" onClick={save}>SAVE ALL CHANGES <ArrowIcon /></button><button className="admin-button" type="button" onClick={reset}>RESET STARTER DATA</button></div><span className="admin-save-status">{message}</span></div></section>

      <div className="admin-toolbar"><span><i /> {data.event.name || '8iT EVENT'} // DATA EDITOR</span><div><button type="button" onClick={exportData}>EXPORT JSON</button><button type="button" onClick={() => importRef.current?.click()}>IMPORT JSON</button><input ref={importRef} type="file" accept="application/json" onChange={importData} hidden /></div></div>

      <Panel number="01" title="EVENT SIGNAL" copy="Dates, room details, and the countdown target shown on the public site."><div className="admin-fields admin-fields--three"><Field label="CAMPAIGN NAME" value={data.event.name} onChange={(value) => updateEvent('name', value)} /><Field label="SERIES LINE" value={data.event.series} onChange={(value) => updateEvent('series', value)} /><Field label="SHORT DATE LINE" value={data.event.shortDates} onChange={(value) => updateEvent('shortDates', value)} /><Field label="EVENT START (ISO)" value={data.event.startAt} onChange={(value) => updateEvent('startAt', value)} placeholder="2026-09-24T18:00:00-06:00" /><Field label="LOCATION" value={data.event.location} onChange={(value) => updateEvent('location', value)} /><Field label="VENUE" value={data.event.venue} onChange={(value) => updateEvent('venue', value)} /><Field label="ADDRESS" value={data.event.address} onChange={(value) => updateEvent('address', value)} /><Field label="OFFICIAL URL" value={data.event.officialUrl} onChange={(value) => updateEvent('officialUrl', value)} /><Field label="TICKET URL" value={data.event.ticketsUrl} onChange={(value) => updateEvent('ticketsUrl', value)} /></div></Panel>

      <Panel number="02" title="LIVE SCORE" copy="The score card, round progress, and now-playing state. Use any labels the desk needs on tournament day."><div className="admin-fields admin-fields--three"><Field label="TEAM A" value={data.liveMatch.teamA} onChange={(value) => updateLiveMatch('teamA', value)} /><Field label="TEAM B" value={data.liveMatch.teamB} onChange={(value) => updateLiveMatch('teamB', value)} /><Field label="ROUND LABEL" value={data.liveMatch.roundLabel} onChange={(value) => updateLiveMatch('roundLabel', value)} /><Field label="TEAM A SCORE" value={data.liveMatch.scoreA} onChange={(value) => updateLiveMatch('scoreA', value)} /><Field label="TEAM B SCORE" value={data.liveMatch.scoreB} onChange={(value) => updateLiveMatch('scoreB', value)} /><Field label="STATUS LINE" value={data.liveMatch.status} onChange={(value) => updateLiveMatch('status', value)} /><Field label="ROUND PROGRESS %" type="number" value={data.liveMatch.progress} onChange={(value) => updateLiveMatch('progress', Math.min(100, Math.max(0, Number(value) || 0)))} /></div></Panel>

      <Panel number="03" title="SCHEDULE" copy="Edit the four-day rhythm without touching the page code."><div className="admin-table admin-table--schedule"><div className="admin-table__labels"><span>DAY</span><span>DATE</span><span>MOMENT</span><span>PUBLIC COPY</span></div>{data.schedule.map((row, rowIndex) => <div className="admin-table__row" key={row[0]}><Field label={`DAY ${rowIndex + 1}`} value={row[0]} onChange={(value) => updateArrayCell('schedule', rowIndex, 0, value)} /><Field label="DATE" value={row[1]} onChange={(value) => updateArrayCell('schedule', rowIndex, 1, value)} /><Field label="MOMENT" value={row[2]} onChange={(value) => updateArrayCell('schedule', rowIndex, 2, value)} /><Field label="PUBLIC COPY" value={row[3]} onChange={(value) => updateArrayCell('schedule', rowIndex, 3, value)} /></div>)}</div></Panel>

      <Panel number="04" title="BRACKET" copy="Replace TBDs, team names, scores, and status labels as the tournament unfolds."><div className="admin-bracket-grid">{data.bracket.map((round, roundIndex) => <div className="admin-bracket-round" key={`${round.title}-${roundIndex}`}><Field label={`ROUND ${roundIndex + 1} TITLE`} value={round.title} onChange={(value) => updateBracketTitle(roundIndex, value)} />{round.rows.map((row, rowIndex) => <div className="admin-bracket-match" key={`${roundIndex}-${rowIndex}`}>{row.map((value, cellIndex) => <Field label={['TEAM A', 'SCORE A', 'TEAM B', 'SCORE B', 'STATUS'][cellIndex]} value={value} onChange={(nextValue) => updateBracketCell(roundIndex, rowIndex, cellIndex, nextValue)} key={`${roundIndex}-${rowIndex}-${cellIndex}`} />)}</div>)}</div>)}</div></Panel>

      <Panel number="05" title="KILL FEED" copy="Short, sharp desk lines that rotate through the public now-playing panel."><div className="admin-table"><div className="admin-table__labels"><span>ACTOR</span><span>ACTION</span><span>DETAIL</span></div>{data.killFeed.map((row, rowIndex) => <div className="admin-table__row admin-table__row--three" key={`${row[0]}-${rowIndex}`}><Field label="ACTOR" value={row[0]} onChange={(value) => updateArrayCell('killFeed', rowIndex, 0, value)} /><Field label="ACTION" value={row[1]} onChange={(value) => updateArrayCell('killFeed', rowIndex, 1, value)} /><Field label="DETAIL" value={row[2]} onChange={(value) => updateArrayCell('killFeed', rowIndex, 2, value)} /></div>)}</div></Panel>

      <Panel number="06" title="ROSTER" copy="Update the squad names, roles, player status, and POV channel slugs in seconds."><div className="admin-table"><div className="admin-table__labels"><span>PLAYER</span><span>ROLE</span><span>STATUS</span><span>POV CHANNEL</span></div>{data.roster.map((row, rowIndex) => <div className="admin-table__row" key={`${row[0]}-${rowIndex}`}><Field label={`PLAYER ${rowIndex + 1}`} value={row[0]} onChange={(value) => updateArrayCell('roster', rowIndex, 0, value)} /><Field label="ROLE" value={row[1]} onChange={(value) => updateArrayCell('roster', rowIndex, 1, value)} /><Field label="STATUS" value={row[2]} onChange={(value) => updateArrayCell('roster', rowIndex, 2, value)} /><Field label="TWITCH SLUG (OPTIONAL)" value={row[3] || ''} placeholder="leave blank if none" onChange={(value) => updateArrayCell('roster', rowIndex, 3, value || null)} /></div>)}</div></Panel>

      <section className="admin-footer-card"><div><p className="admin-kicker">THE FAST PATH</p><h2>EDIT.<br /><em>SAVE.</em><br />GO LIVE.</h2></div><div><p>These controls are intentionally local-first for tournament day. For a true multi-device operator dashboard, connect the same data shape to a small backend later. Until then, this gets the desk moving in seconds.</p><button className="admin-button admin-button--primary" type="button" onClick={save}>SAVE + PUSH TO PUBLIC TAB <ArrowIcon /></button></div></section>
    </main>
  </div>;
}
